// Sample content for Product Genesis
// Categories: vision | strategy | development | marketing | sales | operations
// Sub-categories (only for development): discovery | dev | testing | uiux | cicd
// Types: essay | note | video | case-study | thought

window.PG_CATEGORIES = [
  {
    id: "vision",
    n: "01",
    label: "Vision",
    blurb: "Where product design is heading when intelligence is a primitive.",
    sub: null,
  },
  {
    id: "strategy",
    n: "02",
    label: "Strategy",
    blurb: "Picking the right bets, moats, and roadmaps for AI-native products.",
    sub: null,
  },
  {
    id: "development",
    n: "03",
    label: "Development",
    blurb: "Discovery through CI/CD — the full build loop, rewired for AI.",
    sub: [
      { id: "discovery", label: "Discovery" },
      { id: "dev",       label: "Development" },
      { id: "testing",   label: "Testing" },
      { id: "uiux",      label: "UI / UX" },
      { id: "cicd",      label: "CI / CD" },
    ],
  },
  {
    id: "marketing",
    n: "04",
    label: "Marketing",
    blurb: "Telling the story of products that learn and surprise their users.",
    sub: null,
  },
  {
    id: "sales",
    n: "05",
    label: "Sales",
    blurb: "Pricing, pitching, and closing AI deals with skeptical buyers.",
    sub: null,
  },
  {
    id: "operations",
    n: "06",
    label: "Operations",
    blurb: "Running an AI product without burning the kitchen down.",
    sub: null,
  },
];

window.PG_POSTS = [
  // ── VISION ──────────────────────────────────────────────────────────────
  {
    id: "v6",
    cat: "vision",
    type: "video",
    title: "The State of AI in UX & Product Design 2026 — panel discussion.",
    dek: "Six practitioners take stock of where AI-assisted design actually stands: what's working, what's hype, and what's coming next.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 45,
    videoLabel: "Panel · UX & Product Design 2026",
    videoLength: "44:52",
    sourceUrl: "https://www.youtube.com/watch?v=xu_mWjuXUfw",
    sourceLabel: "YouTube",
  },
  {
    id: "v4",
    cat: "vision",
    type: "essay",
    title: "AI removes execution friction. It doesn't fix the thinking upstream.",
    dek: "The gap between product strategy and delivery is widening in 2026 — not closing. Here's why AI is partly to blame.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 6,
    feature: true,
    tone: "warm",
    sourceUrl: "https://antmurphy.medium.com/how-product-is-changing-in-2026-78a08f150aca",
    sourceLabel: "Ant Murphy · Medium",
    body: [
      "Product management is not dying — it's being repriced. Ant Murphy's latest analysis of the 2026 job market cuts through the 'PM is dead' narrative with an inconvenient data point: 42,000 open PM roles, recovered to pre-2020 levels. The discipline isn't collapsing. It's being asked to justify itself in terms it historically avoided: revenue, margin, and bottom-line impact.",
      "The significant shift Murphy identifies is not in headcount but in mandate. Companies that spent 2021–2024 optimising for growth are now optimising for profitability. That changes which product decisions get made, how they get justified, and who gets to make them. PMs who built careers on 'growth metrics' are finding that language no longer opens doors.",
      "Meanwhile, AI is accelerating the wrong half of the problem. 94% of PMs now use AI tools daily, saving 1–2 hours of execution time. But 95% of enterprise AI pilots still fail to deliver measurable ROI. The execution gets faster. The thinking stays as hard as ever. AI compresses the distance between decision and output — which means bad decisions now arrive faster.",
      "What survives this compression is judgment. Strategic foresight. The ability to connect a product decision to a financial outcome in a room full of skeptics. The PMs who thrive in 2026 won't be the best at managing roadmaps. They'll be the best at making the case for them.",
    ],
  },
  {
    id: "v5",
    cat: "vision",
    type: "note",
    title: "MX design: you're no longer designing only for humans.",
    dek: "AI agents increasingly navigate, evaluate, and act on your product. Machine Experience design is the discipline that comes next.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 3,
    sourceUrl: "https://uxpilot.ai/blogs/product-design-trends",
    sourceLabel: "UX Pilot",
    body: [
      "The term 'user experience' assumes a human user. That assumption is quietly eroding. In 2026, an increasing share of interactions with your product are AI-mediated: agents that browse, evaluate, extract, and act — without a human touching a keyboard. UX Pilot calls this MX: Machine Experience design.",
      "MX isn't about making your product look good to robots. It's about whether your product can be understood, navigated, and actioned by an AI on a user's behalf. Structured data, clear affordances, predictable state, semantic markup — the disciplines that made products accessible to screen readers are now the disciplines that make them agent-ready.",
      "Most product teams haven't started thinking about this. The ones that do in the next 12 months will have a head start on a shift that won't be optional by 2027.",
    ],
  },
  {
    id: "v1",
    cat: "vision",
    type: "essay",
    title: "Product design will look nothing like it did in 2023.",
    dek: "The job is no longer to specify behavior. It is to specify intent, evaluate outcomes, and shape what surprise feels like.",
    author: "Genesis",
    date: "May 14, 2026",
    read: 8,
    feature: true,
    tone: "warm",
    body: [
      "For twenty years, product design has been a discipline of certainty. We drew the interface, wrote the copy, specced the empty state, and the software did what we said. That contract is broken.",
      "The new contract is that you specify intent and the product negotiates the rest. Buttons become suggestions. Forms become conversations. Empty states become first turns of dialog. The designer's job is no longer to draw the path — it is to fence the pasture.",
      "This sounds abstract until you sit with it. Then it gets practical fast. You stop asking \"what should this screen look like?\" and start asking \"what should this experience never do?\" You build evaluation harnesses instead of click-paths. You write prompts the way you used to write microcopy.",
      "The teams that thrive in this era will be the ones who treat surprise as a design surface, not a bug. The teams that struggle will be the ones still drawing wireframes for screens that will never render the same way twice.",
    ],
  },
  {
    id: "v2",
    cat: "vision",
    type: "thought",
    title: "The wireframe is dead. The eval is alive.",
    dek: "Six words to put on every product team's wall in 2026.",
    author: "Genesis",
    date: "May 9, 2026",
    read: 1,
  },
  {
    id: "v3",
    cat: "vision",
    type: "video",
    title: "The design process is dead. Why designers can no longer trust it.",
    dek: "Jenny Wen on why the traditional design process fails in a world of AI — and what actually replaces it.",
    author: "Genesis",
    date: "Dec 29, 2025",
    read: 18,
    videoLabel: "Talk · Jenny Wen",
    videoLength: "18:24",
    sourceUrl: "https://www.youtube.com/watch?v=4u94juYwLLM",
    sourceLabel: "YouTube · Jenny Wen",
  },

  // ── STRATEGY ────────────────────────────────────────────────────────────
  {
    id: "s6",
    cat: "strategy",
    type: "video",
    title: "The reality of building an AI company — inside a week of decisions.",
    dek: "Roadmap debates, engineering trade-offs, customer pain points, and scaling problems — unfiltered, from inside a team doing it right now.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 28,
    videoLabel: "Founder doc · AI company building",
    videoLength: "27:14",
    sourceUrl: "https://www.youtube.com/watch?v=PyG8GacsoU4",
    sourceLabel: "YouTube",
  },
  {
    id: "s4",
    cat: "strategy",
    type: "essay",
    title: "Access to the model is not the moat. Here's what is.",
    dek: "In 2026, the winners aren't the teams with the best model access. They're the ones with data that compounds, workflows that lock in, and markets too niche to be worth copying.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 7,
    feature: true,
    tone: "ink",
    sourceUrl: "https://azati.ai/blog/generative-ai-competitive-advantage-real-moat/",
    sourceLabel: "Azati",
    body: [
      "79% of organisations are now investing in generative AI. Only 23% are building anything defensible with it. That gap — between AI adoption and AI advantage — is the defining strategic problem of 2026.",
      "The companies in the 23% share one characteristic: they stopped treating model access as a moat and started treating it as a commodity. They're right. The best foundation models are available to anyone with a credit card. The moat was never the model. It was always what you built around it.",
      "Azati's analysis identifies seven defensibility sources that hold up under competitive pressure: proprietary training data, data network effects, workflow integration depth, transformed business models, domain expertise encoding, operational excellence, and technology stack choices. The concrete contrast: Company A deployed a generic chatbot for 40% cost savings and was copied within three months. Company B fine-tuned on five years of proprietary customer data with deep CRM integration, achieving 70% savings plus new revenue streams — and created something competitors would need years to replicate.",
      "The diagnostic question worth running on your own product: if a well-funded competitor deployed the same foundation model you use next quarter, what would still be hard to copy? If the answer is 'not much,' you're building features, not a moat.",
    ],
  },
  {
    id: "s5",
    cat: "strategy",
    type: "note",
    title: "Strategic AI beats tactical AI by 3.5x. The data is in.",
    dek: "BCG's 2026 research confirms what good product teams already suspected: AI sprints without strategy don't compound. They evaporate.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 3,
    sourceUrl: "https://jetsoftpro.com/blog/ai-product-strategy-2026",
    sourceLabel: "JetSoftPro · BCG",
    body: [
      "BCG's 2026 analysis of generative AI value capture lands on a specific number: organisations that prioritise strategic GenAI applications achieve 3.5x higher long-term value than those chasing quick tactical wins. 3.5x is not a rounding error. It's the difference between a product that compounds and one that churns.",
      "The distinction between strategic and tactical isn't about scale — it's about integration. Tactical AI ships a feature. Strategic AI rewires a workflow, creates a feedback loop, or generates data that makes the next decision better than the last. The first is visible in a sprint demo. The second shows up on a P&L.",
      "Most teams know this intuitively. The BCG data makes it hard to argue with in a planning meeting.",
    ],
  },
  {
    id: "s1",
    cat: "strategy",
    type: "case-study",
    title: "How a 12-person SaaS picked the right AI moat — and avoided three wrong ones.",
    dek: "Workflow lock-in vs. data flywheels vs. model finetuning. A two-month decision compressed into a one-week sprint.",
    author: "Genesis",
    date: "May 11, 2026",
    read: 9,
    feature: true,
    tone: "ink",
    body: [
      "When the leadership team at Lattice* (name changed) brought us in, they were three months into building a custom model. They had spent $180k on compute and another $90k on contractor time. The thing worked. It was also the wrong moat.",
      "We ran a one-week strategy sprint with three exercises. First, we mapped every AI feature on a 2x2 of \"hard to copy\" vs \"valuable to customer.\" Second, we costed each one as if a Series C competitor with $40M was building it next quarter. Third, we asked which of those features made existing customers more valuable, not just new customers more likely.",
      "The custom model lost on every axis. What won was a workflow integration nobody had been excited about — because it locked in the data, and the data compounded.",
      "Six months later the team is profitable on AI features for the first time. The lesson is not that custom models are bad. The lesson is that 'moat' is a verb that has to be tested every quarter.",
    ],
  },
  {
    id: "s2",
    cat: "strategy",
    type: "note",
    title: "Your roadmap should be 6 weeks, not 6 quarters.",
    dek: "Quarterly planning assumes a static world. Your competitors no longer live in one.",
    author: "Genesis",
    date: "May 6, 2026",
    read: 3,
  },
  {
    id: "s3",
    cat: "strategy",
    type: "thought",
    title: "If your AI strategy fits in a tweet, it's probably a feature, not a strategy.",
    author: "Genesis",
    date: "May 2, 2026",
    read: 1,
  },

  // ── DEVELOPMENT ─────────────────────────────────────────────────────────
  {
    id: "d10",
    cat: "development",
    sub: "dev",
    type: "video",
    title: "Full walkthrough: AI coding workflow, every step shown — Matt Pocock.",
    dek: "Not a highlights reel. A complete, unedited session showing how a senior engineer actually moves from spec to shipped code with AI assistance.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 35,
    videoLabel: "Walkthrough · Matt Pocock",
    videoLength: "34:08",
    sourceUrl: "https://www.youtube.com/watch?v=-QFHIoCo-Ko",
    sourceLabel: "YouTube · Matt Pocock",
  },
  {
    id: "d7",
    cat: "development",
    sub: "uiux",
    type: "essay",
    title: "Calm interfaces. Transparent AI. The end of visual theatrics.",
    dek: "As AI features mature, the design trend is moving away from flashy animations and magic moments — toward trust, legibility, and restraint.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 5,
    tone: "sand",
    sourceUrl: "https://elements.envato.com/learn/ux-ui-design-trends",
    sourceLabel: "Envato Elements",
    body: [
      "The AI design aesthetic of 2024 was spectacle: glowing gradients, particle effects, animated responses that announced themselves. It worked as a novelty signal. It's exhausting as a daily interface. The 2026 correction is underway, and it has a name: calm design.",
      "Calm interfaces reduce cognitive load through simplified flows and minimal decision points. The core principle is that a well-designed AI feature should feel like it's already done the thinking — not like it's performing thinking at you. Motion is kept, but redirected: animations now clarify system states and progress rather than decorating them.",
      "The harder shift is transparency. Users have learned enough about AI to be appropriately skeptical. They want to know how suggestions are generated. They want override controls, not algorithmic lock-in. They want to understand what the system is confident about and where it's guessing. Designs that obscure this are increasingly feeling dishonest rather than magical.",
      "Accessibility is also being pulled into the centre. Features like keyboard navigation, high contrast modes, and clear focus states — long treated as compliance work — are being built in from day one. The most inclusive designs and the most AI-forward designs are converging on the same principles.",
    ],
  },
  {
    id: "d8",
    cat: "development",
    sub: "dev",
    type: "essay",
    title: "Specs. Small chunks. Always review. Addy Osmani's LLM workflow.",
    dek: "The Chrome DevTools lead at Google shares how he's actually shipping with AI assistance in 2026 — and the discipline that keeps it from becoming chaos.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 8,
    feature: true,
    tone: "accent",
    sourceUrl: "https://addyo.substack.com/p/my-llm-coding-workflow-going-into",
    sourceLabel: "Addy Osmani · Substack",
    body: [
      "Addy Osmani leads Chrome DevTools at Google. His post on LLM coding workflow has circulated widely for good reason: it's specific, practitioner-tested, and at odds with the 'just vibe code' advice that dominates the discourse.",
      "The workflow starts before any code is written. Osmani creates a detailed spec with the AI — establishing shared understanding of what's being built, why, and what constraints apply. Then he breaks work into small, bounded tasks completed one at a time. His observation: LLMs do their best work with focused prompts. Feed one a whole codebase and ask it to build something, and you get inconsistency. Feed it one well-scoped task and you get something reviewable.",
      "The review step is non-negotiable. He treats AI output the way a senior engineer treats output from a capable junior: read it, understand it, verify it. He recommends integrating strict CI/CD checks — tests and linters — that catch AI mistakes automatically, and using a second AI model to review code from the first. AI-on-AI code review is now a real practice, not a thought experiment.",
      "The operational details compound over time. A CLAUDE.md file in each project encodes style preferences and constraints. Git worktrees sandbox parallel AI experiments so the main branch stays clean. Commits happen after every successful task as save points. The cumulative effect: an AI-augmented workflow that amplifies productivity without surrendering accountability — what he calls being 'proudly accountable for the software we produce, however we produce it.'",
    ],
  },
  {
    id: "d9",
    cat: "development",
    sub: "testing",
    type: "essay",
    title: "Teams shipping reliable AI aren't lucky. They're systematic.",
    dek: "What a real LLM eval pipeline looks like in 2026 — and why your automated scores might be saying 'great' while users are clicking thumbs-down.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 7,
    sourceUrl: "https://dev.to/pockit_tools/llm-evaluation-and-testing-how-to-build-an-eval-pipeline-that-actually-catches-failures-before-5e3n",
    sourceLabel: "DEV Community",
    body: [
      "The teams shipping AI features that hold up in production don't have better models. They have better evals. An LLM eval pipeline — automated tests that catch failures before users do — is now the difference between AI features that work and AI features that embarrass you at the worst moment.",
      "The most actionable insight from this guide: your evals need to predict user satisfaction, not just pass your own rubric. If automated scores say 'great' while users are clicking thumbs-down, your evals are miscalibrated. The fix is to regularly compare automated scores against real user feedback signals — thumbs, ratings, session abandonment — and adjust the rubric until they align.",
      "For teams starting from scratch, the 2026 recommendation is Promptfoo or DeepEval for quick wins, then custom eval layers as needs get specific. DeepEval integrates directly with pytest and produces per-metric pass/fail outcomes with configurable thresholds. RAGAS is the choice for retrieval-augmented generation. The tool matters less than the discipline: treat your eval dataset with the same care as your production code.",
      "The teams who invested in eval infrastructure early — even when it felt like overhead — are the ones with the confidence to ship fast. The pipeline is what makes speed safe.",
    ],
  },
  {
    id: "d1",
    cat: "development",
    sub: "discovery",
    type: "essay",
    title: "Customer interviews when users can't articulate what they want from AI.",
    dek: "The Jobs-To-Be-Done playbook works — but only after you strip out the prompts your interviewees absorbed from Twitter.",
    author: "Genesis",
    date: "May 13, 2026",
    read: 6,
    tone: "sand",
    body: [
      "Half of the AI feature interviews I sit in on go like this: the user describes the product they think they're supposed to want, in the language of LinkedIn posts they read last week. \"I want it to be more agentic.\" \"I want it to remember context.\" \"I want it to be like a copilot.\"",
      "These are not signals. They are echoes. The actual signal is in the unguarded fifteen seconds after you ask a follow-up question they weren't expecting. Ask them to walk you through the last time the current product disappointed them. Ask them what they did next. Ask them what they Googled. That's where the real shape of the job lives.",
      "A good rule: if your interview notes could be ChatGPT's idea of an AI feature wish list, you didn't run an interview. You ran a focus group with itself.",
    ],
  },
  {
    id: "d2",
    cat: "development",
    sub: "dev",
    type: "essay",
    title: "Five LLM patterns that ship — and three that always melt down.",
    dek: "What we learned shipping AI features across nine codebases over twelve months.",
    author: "Genesis",
    date: "May 8, 2026",
    read: 11,
    feature: true,
    tone: "accent",
    body: [
      "After a year of shipping into production, the patterns sort themselves into two piles. The ones in the first pile work in 80% of cases and degrade gracefully in the other 20%. The ones in the second pile work in 95% of cases and humiliate you in the other 5%.",
      "PATTERN ONE that works: classify-then-route. Use a cheap model to decide what kind of request this is, then route to the right specialized handler. Boring. Reliable.",
      "PATTERN TWO that works: extract-and-confirm. Pull structured data out, but always show the user what you extracted before you act on it. Confirmation is the cheapest insurance you can buy.",
      "PATTERN THREE that always melts down: open-ended chat as the primary interface. Users won't use it the way your demo shows. They will paste paragraphs. They will say \"do it.\" They will get angry when it does.",
      "The full list — including the eval harness we use to choose between them — lives in the case study below.",
    ],
  },
  {
    id: "d3",
    cat: "development",
    sub: "testing",
    type: "note",
    title: "Eval pipelines are now first-class citizens.",
    dek: "If your CI/CD runs unit tests but not LLM evals, you're shipping blind.",
    author: "Genesis",
    date: "May 4, 2026",
    read: 4,
  },
  {
    id: "d4",
    cat: "development",
    sub: "uiux",
    type: "essay",
    title: "Streaming is the new loading state.",
    dek: "Three UI primitives that make non-deterministic outputs feel like craft.",
    author: "Genesis",
    date: "Apr 28, 2026",
    read: 5,
    tone: "warm",
    body: [
      "The spinner used to mean: something is happening. Now it means: we have no idea what to show you. That's a regression.",
      "The three primitives that replace it are progressive disclosure (show the skeleton, fill the body), confidence-tinted text (faded while uncertain, solidifying as the model commits), and visible reasoning (a quiet scrubbable trace of what the model considered).",
      "None of these are exotic. All of them are missing from 90% of the AI products I audit.",
    ],
  },
  {
    id: "d5",
    cat: "development",
    sub: "cicd",
    type: "video",
    title: "How to build AI evals in 2026 — step by step, no hype.",
    dek: "Hamel Husain and Shreya Shankar walk through the complete eval pipeline they've taught to over 2,000 PMs and engineers.",
    author: "Genesis",
    date: "Jan 2026",
    read: 45,
    videoLabel: "Workshop · Hamel Husain & Shreya Shankar",
    videoLength: "44:21",
    sourceUrl: "https://www.youtube.com/watch?v=J7N9FMouSKg",
    sourceLabel: "YouTube · Hamel Husain",
  },
  {
    id: "d6",
    cat: "development",
    sub: "discovery",
    type: "thought",
    title: "Users won't tell you their job is to feel competent at work. But it is.",
    author: "Genesis",
    date: "Apr 18, 2026",
    read: 1,
  },

  // ── MARKETING ───────────────────────────────────────────────────────────
  {
    id: "m6",
    cat: "marketing",
    type: "video",
    title: "The next 5 years of product marketing: competing with AI, winning with storytelling.",
    dek: "AI can replicate tactics. It can't replicate a story only you can tell. What that means for every product marketer in the next five years.",
    author: "Genesis",
    date: "Sep 25, 2025",
    read: 28,
    videoLabel: "Talk · Product Marketing Alliance",
    videoLength: "27:42",
    sourceUrl: "https://www.youtube.com/watch?v=-wu7h64Ey6g",
    sourceLabel: "YouTube · Product Marketing Alliance",
  },
  {
    id: "m4",
    cat: "marketing",
    type: "note",
    title: "AI isn't levelling the marketing playing field. It's widening it.",
    dek: "Marketing Dive's 2026 predictions land on an uncomfortable truth: AI is making great marketers far better and mediocre ones invisible.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 4,
    sourceUrl: "https://www.marketingdive.com/news/marketing-predictions-for-2026/809124/",
    sourceLabel: "Marketing Dive",
    body: [
      "The optimistic narrative about AI in marketing is that it democratises capability — giving small teams the output of large ones. Marketing Dive's 2026 predictions challenge that directly: AI is fuelling polarity, not parity. The gap between teams using AI well and those drowning in generated noise is growing, not shrinking.",
      "The pattern is predictable in retrospect. AI amplifies what's already there. Teams with strong strategic thinking, clear positioning, and rigorous creative standards use AI to produce more of that. Teams without those foundations use AI to produce more content faster — which means more mediocre content, at higher volume, in an increasingly saturated channel.",
      "The implication for product marketing: AI doesn't replace the hard work of understanding your customer and sharpening your message. It removes the excuse for not doing it at scale.",
    ],
  },
  {
    id: "m5",
    cat: "marketing",
    type: "thought",
    title: "Customers don't buy your model. They buy what changes for them.",
    dek: "Position on the outcome you create, not the capability underneath it. This rule matters more in AI than anywhere else.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 1,
    sourceUrl: "https://ainna.ai/resources/faq/go-to-market-strategy-faq",
    sourceLabel: "Ainna AI",
  },
  {
    id: "m1",
    cat: "marketing",
    type: "case-study",
    title: "How we 4x'd demo-to-trial on an AI feature by changing the narrative, not the product.",
    dek: "The same feature, two pitches. One sold the model. The other sold the moment.",
    author: "Genesis",
    date: "May 12, 2026",
    read: 7,
    feature: true,
    tone: "ink",
    body: [
      "The team was leading every demo with model specs. \"It's GPT-4.1 with our fine-tune, with RAG over your knowledge base, with a custom router.\" Prospects nodded politely and didn't convert.",
      "We rewrote the first ninety seconds of the demo. Now it opens with a screenshot of an exhausted PM at 11pm with 47 unread Slack messages. The product appears in the next slide, and the line is: \"by the time you wake up, this thread is summarized, the decisions are extracted, and the open questions are queued up.\"",
      "Same product. Same model. 4x conversion in the next quarter.",
      "AI products do not sell themselves on capability. They sell themselves on the moment of relief they create.",
    ],
  },
  {
    id: "m2",
    cat: "marketing",
    type: "note",
    title: "Stop putting \"AI\" in your H1. Put what changes for the user.",
    dek: "Every \"AI-powered\" headline is a coordination failure between marketing and product.",
    author: "Genesis",
    date: "May 5, 2026",
    read: 2,
  },
  {
    id: "m3",
    cat: "marketing",
    type: "thought",
    title: "Demos are storytelling. Storytelling is editing. Cut your demo in half.",
    author: "Genesis",
    date: "Apr 27, 2026",
    read: 1,
  },

  // ── SALES ───────────────────────────────────────────────────────────────
  {
    id: "sa6",
    cat: "sales",
    type: "video",
    title: "The ultimate guide to selling AI in 2025 — for founders and sales reps.",
    dek: "What objections are real, which are stalling, and how to move enterprise buyers who are genuinely uncertain about AI ROI.",
    author: "Genesis",
    date: "Jun 16, 2025",
    read: 35,
    videoLabel: "Guide · Selling AI",
    videoLength: "34:50",
    sourceUrl: "https://www.youtube.com/watch?v=XfPQz1hLnD4",
    sourceLabel: "YouTube",
  },
  {
    id: "sa4",
    cat: "sales",
    type: "essay",
    title: "The AI pricing reckoning: renewals are here and buyers want predictability.",
    dek: "2025 was 'AI at all costs.' 2026 is the first renewal cycle. 87% of enterprise buyers now demand fixed, predictable pricing — and vendors still on token pricing are losing deals.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 8,
    feature: true,
    tone: "ink",
    sourceUrl: "https://www.chargebee.com/blog/pricing-ai-agents-playbook/",
    sourceLabel: "Chargebee",
    body: [
      "2025 was the year of AI adoption at all costs. Budget scrutiny was minimal, renewal cycles hadn't hit, and 'AI-powered' was sufficient justification for a purchase. 2026 is different. The first cohort of enterprise AI buyers is now at renewal — and they've had a year to measure whether the investment delivered. Many haven't.",
      "McKinsey's data is blunt: eight in ten companies use generative AI, yet just as many report no significant bottom-line impact. That's the renewal conversation vendors are now walking into. The product hasn't changed. The buyer's patience has.",
      "Chargebee's playbook identifies three pricing models surviving this scrutiny: outcome-based (charging per resolved issue or qualified lead, as Intercom and HubSpot Breeze now do), action-based (metering workflow steps), and hybrid models combining a flat base with usage overages. What they share is legibility — the customer can calculate their bill before it arrives. Vendors still pricing on tokens or raw API consumption are being disqualified early, not because the price is wrong but because the unpredictability is unacceptable to procurement.",
      "One further pressure point: LLM costs are dropping roughly 10x per year. Vendors who lock in 2025-era pricing and hold it will look increasingly expensive relative to underlying cost. The ones who build pricing that adjusts with the market will have a structural advantage in every renewal conversation.",
    ],
  },
  {
    id: "sa5",
    cat: "sales",
    type: "note",
    title: "Outcome-based pricing removes the buyer's biggest objection.",
    dek: "When you price on results, the enterprise buyer's core fear — 'what if this doesn't deliver?' — disappears from the negotiation.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 3,
    sourceUrl: "https://futurumgroup.com/press-release/are-outcome-based-and-hybrid-ai-pricing-models-rewriting-the-vendor-playbook/",
    sourceLabel: "Futurum Group",
    body: [
      "Futurum's 1H 2026 survey of enterprise AI buyers breaks down pricing preferences: 43% prefer consumption-based models, 27% favour outcome-based structures, and the remainder want flat-rate predictability above all. The most interesting number is the 27% — buyers willing to pay more per outcome if it means their risk disappears.",
      "HubSpot's April 2026 shift with Breeze AI is the concrete case: the Customer Agent moved from $1 per conversation to $0.50 per resolved conversation. The Prospecting Agent moved from a monthly charge per enrolled contact to $1 per qualified lead. Price-per-unit went up. Conversion went up. Because the buyer's objection — 'what if it doesn't work?' — became structurally impossible.",
      "Outcome-based pricing is not just a commercial model. It's a product statement: we're confident enough in what we deliver to attach our revenue to it.",
    ],
  },
  {
    id: "sa1",
    cat: "sales",
    type: "essay",
    title: "Selling AI to skeptical enterprise buyers — the four objections, mapped.",
    dek: "Compliance. Cost. Determinism. Headcount. None of these are real objections until you read between them.",
    author: "Genesis",
    date: "May 10, 2026",
    read: 7,
    tone: "sand",
    body: [
      "Enterprise buyers are not skeptical about AI. They are skeptical about being the person who said yes to AI and got it wrong. That's a very different sale.",
      "Compliance is rarely the actual concern. It's the language the actual concern hides behind. The actual concern is: if this thing hallucinates a customer's account number, am I the one who has to explain it to my CEO?",
      "Cost is rarely the actual concern either. It's: if this thing gets twice as expensive next quarter, am I the one who has to defend the renewal?",
      "The pitch that wins is the pitch that gives the buyer cover. Not a feature list. A defensible narrative they can repeat in their next leadership meeting.",
    ],
  },
  {
    id: "sa2",
    cat: "sales",
    type: "note",
    title: "Usage-based pricing only works if your usage is legible.",
    dek: "If the customer can't predict their bill, they will price-anchor on the worst month and churn.",
    author: "Genesis",
    date: "May 3, 2026",
    read: 3,
  },
  {
    id: "sa3",
    cat: "sales",
    type: "thought",
    title: "Procurement's first question is never about the product. Plan accordingly.",
    author: "Genesis",
    date: "Apr 25, 2026",
    read: 1,
  },

  // ── OPERATIONS ──────────────────────────────────────────────────────────
  {
    id: "o6",
    cat: "operations",
    type: "video",
    title: "Cut your LLM costs by 50% — 3 production-tested techniques.",
    dek: "Three specific optimisations — not theory — that have each cut inference spend by double digits in real production deployments.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 14,
    videoLabel: "Production tips · LLM cost",
    videoLength: "13:47",
    sourceUrl: "https://www.youtube.com/watch?v=yTfkZ-Eusc8",
    sourceLabel: "YouTube",
  },
  {
    id: "o4",
    cat: "operations",
    type: "essay",
    title: "Agentic AI uses 30x more tokens. Your cost model is probably wrong.",
    dek: "Inference costs dropped 280x in two years — but enterprise AI bills are still exploding. The culprit: agents, which consume 5–30x more tokens per task than chatbots.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 7,
    feature: true,
    tone: "accent",
    sourceUrl: "https://oplexa.com/ai-inference-cost-crisis-2026/",
    sourceLabel: "Oplexa",
    body: [
      "Here's the paradox catching enterprise AI teams off-guard: per-token inference costs have dropped 280x over two years. Enterprise AI bills have increased 320% over the same period. Both numbers are true. Understanding why requires understanding what changed.",
      "What changed is the architecture. Simple chatbot: one prompt, one response, bounded tokens. Agentic workflow: planning, tool calls, retrieval, evaluation, revision — each step consuming tokens. Agentic workflows run 10–20x more tokens than simple queries. Add RAG and context inflation runs another 3–5x. Add always-on monitoring agents and you've built a system that never stops spending.",
      "The financial picture is stark. Average enterprise AI spend has grown from $1.2 million annually in 2024 to $7 million in 2026. Inference now represents 85% of the enterprise AI budget, per AnalyticsWeek's 2026 report. And most teams haven't modelled the further pressure point: current API pricing is partially subsidised. Oplexa projects a 30–50% increase within 18 months as providers normalise their economics.",
      "The operational response is cost allocation before the spike, not after it. Tag AI workloads by model, team, deployment stage, and product feature. Track cost per active user, cost per session, and cost per successful outcome — the third being the one that tells you whether your AI features are actually profitable.",
    ],
  },
  {
    id: "o5",
    cat: "operations",
    type: "note",
    title: "Tag your AI workloads now. Before the bill makes you do it.",
    dek: "The teams that understand their AI costs aren't smarter — they just tagged their workloads by model, team, and feature before the spending compounded.",
    author: "Genesis",
    date: "May 20, 2026",
    read: 4,
    sourceUrl: "https://www.cloudzero.com/blog/ai-costs/",
    sourceLabel: "CloudZero",
    body: [
      "Most AI cost conversations happen after the crisis. A bill arrives that's 3x the expected amount, finance asks for an explanation, and the engineering team discovers they have no idea which feature, team, or model version is responsible. The conversation that follows is unpleasant and avoidable.",
      "CloudZero's recommendation is deceptively simple: tag AI workloads at the job level before you scale. Model, team, deployment stage, product feature — four dimensions that let you slice a cost spike in minutes rather than days. This isn't AI-specific advice; it's cloud cost management applied to a new resource type. Because AI inference arrived fast and costs seemed manageable at first, most teams skipped the tagging step.",
      "The teams running the most operationally mature AI products track four metrics: cost per active user, cost per session, cost per successful outcome, and 90th-percentile latency. The third is the rare one. It's also the one that tells you whether your AI feature is profitable — or just popular.",
    ],
  },
  {
    id: "o1",
    cat: "operations",
    type: "essay",
    title: "Running cost-controlled AI at scale without strangling the product.",
    dek: "The three levers that matter, the four dashboards we run, and the meeting cadence that keeps it sane.",
    author: "Genesis",
    date: "May 7, 2026",
    read: 8,
    feature: true,
    tone: "accent",
    body: [
      "Cost is the silent killer of AI product roadmaps. Not because models are expensive — they aren't, much, anymore — but because nobody owns the line item until it has already eaten the margin.",
      "The three levers that matter: model selection (cheap by default, expensive on demand), caching (semantic and exact), and prompt size (every system prompt should have a budget). Everything else is downstream of these three.",
      "The four dashboards we run with every client: cost per active user, cost per session, cost per successful outcome, and 90th percentile latency. The third is the one most teams skip. It's the one that tells you whether you're profitable.",
    ],
  },
  {
    id: "o2",
    cat: "operations",
    type: "note",
    title: "Build the AI ops team before you need one. Not after.",
    dek: "The team you need looks more like SRE than ML. Hire accordingly.",
    author: "Genesis",
    date: "May 1, 2026",
    read: 4,
  },
  {
    id: "o3",
    cat: "operations",
    type: "video",
    title: "How I cut token costs by 90% — an AI cost optimisation guide.",
    dek: "The specific changes one startup made to save over $1 million a year in LLM spend — without switching models or cutting features.",
    author: "Genesis",
    date: "Apr 4, 2026",
    read: 22,
    videoLabel: "Case study · Token cost optimisation",
    videoLength: "21:15",
    sourceUrl: "https://www.youtube.com/watch?v=4x4nM0uPmg0",
    sourceLabel: "YouTube",
  },
];
