sonar.organization=gerald-o-connor
sonar.projectKey=productgenesis

sonar.sources=.
sonar.exclusions=node_modules/**,reviews/**,uploads/**,.github/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
